version: '3.4'
services:
    webapi:
        image: employees.api
        build:
          context: .
          dockerfile: src/Employees.Api/Dockerfile       
        ports:
           - 5000:80 
        depends_on:
            - db       
            
    db:
        image: "mcr.microsoft.com/mssql/server"        
        environment:          
            ACCEPT_EULA: "Y"   
  